export { Transition } from './Transition'
export { type TransitionProps } from './Transition'
export { presetTransitions } from './preset-transitions'
export type { PresetTransition, PresetTransitionName, PresetTransitionStyles } from './preset-transitions'
export { setGlobalConfig } from './global-config'
